### ISSUE TITLE
Use bin-wrapper instead

### ISSUE THREAD

**Issue by forivall** [jamsyoung/jq-cli-wrapper#3]
Mainly so that the binary doesn't need to be bundled in this repository (though, luckily, jq's binaries are pretty small, so you could get away with not trimming the history)

https://github.com/kevva/bin-wrapper

examples: https://github.com/imagemin/optipng-bin https://github.com/purescript-contrib/node-purescript-bin

**Comment by jamsyoung** [comment]
Thank you! I was not familiar w/ bin-wrapper.

coming soon... _(sorry it took 2 years)_
