### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by crazy4groovy** [jamsyoung/jq-cli-wrapper#6]
```
C:\Temp>npm install --global jq-cli-wrapper

> jq-cli-wrapper@0.4.0 preinstall C:\Users\admin\AppData\Roaming\npm\node_modules\.staging\jq-cli-wrapper-e1ab1d7a
> scripts/link-proper-binary.sh

'scripts' is not recognized as an internal or external command, operable program or batch file.
```

Windows 7 64 bit
Node v6.9.1

**Comment by felixSchl** [comment]
Experiencing the same problem. Changing it to `./scripts/link-proper-binary.sh` should fix it, I think.

**Comment by jamsyoung** [comment]
Ahh, windows.  This package only has the binaries for linux and macOS.  I have never added Windows support because I don't have a convenient way to test it.
